### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Aks-4125** [Ahmed-Abdelmeged/PagingLibraryWithRxJava#2]
I am getting crash on app launch. 
this may help.

`2018-10-30 11:20:23.878 15274-15274/com.ahmedabdelmeged.pagingwithrxjava E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ahmedabdelmeged.pagingwithrxjava, PID: 15274
    java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.ahmedabdelmeged.pagingwithrxjava-9-68qfJ9ZVJK7QEmq0H__g==/split_lib_dependencies_apk.apk)
        at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
        at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
        at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
        at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:67)
        at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:753)
        at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
        at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
        at android.support.v7.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:621)
        at android.support.v7.app.AppCompatDelegateImplV9.onTitleChanged(AppCompatDelegateImplV9.java:631)
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.ahmedabdelmeged.pagingwithrxjava.java.ui.MainActivity.onCreate(MainActivity.java:48)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by amirisback** [comment]
I just updated this project, haven't merged it yet but you can see it here https://github.com/anacadecodes/PagingLibraryWithRxJava
